Time-Locked Sales
asyncart/async-blueprint pull request #31
Opened 2022-08-03 19:03 UTC by samwise2

This PR adds `saleEndTimestamp` to Blueprints. `saleEndTimestamp` is an optional field in the `Blueprints` struct which prevents purchases of `Blueprints` after time has exceeded its value. If it is not specified (0) then purchases may continue until capacity runs out.

2022-08-03 19:25 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        uint256 saleEndTimestamp,
we might also want this in the `BlueprintPrepared` event, @conlan ?

2022-08-03 19:27 UTC, samwise2 commented on test/sales-tests.js
> +    // TODO: consider a test that shows you can't pause a sale who's end timestamp has passed...but maybe we don't want this if we want the minter to be able
Let's consider this. It's a bit strange because there are modifiers on pauseSale, unpauseSale, beginSale etc. which constrain the minter to only make valid `SaleState` transitions, but as is, the minter could always get around that and do whatever they want by hitting `updateBlueprintSettings` which has effectively no restrictions...

2022-08-03 19:27 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        // Do we want to validate that this is an accurate transition? i.e. not_started -> paused would be invalid, or enforce the modifiers on pause/unpause sale etc.
i.e. this

2022-08-03 21:23 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        uint256 saleEndTimestamp;
So solidity packs variables into 256 bit spots. If you modify the order of variables in a struct you can pack them efficiently, to take up less space. For example, the variables from `mintAmountArtist` down to `maxPurchaseAmount` fit in a 256-bit space. We should consider making the `saleEndTimestamp` a `uint128`, and moving it down next to `price`, as it and `price` would be packed into 256 bits. 2^127 seconds in unix timestamp is going to take us past the end of the universe, as far as I can tell, so we should be safe

2022-08-03 21:25 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        require(_isSaleOngoing(_blueprintID), "Sale of blueprint not currently ongoing");
I would shorten the message string here to save gas. "Sale not ongoing" is enough as the main consumers of the contract will be us, who can identify what the semantic of the error is by looking at the contract

2022-08-03 21:27 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        require(_saleEndTimestamp == 0 || _saleEndTimestamp > block.timestamp, "Sale end timestamp is a past time");
same thing here wrt to message length. I would also consider switching the conditionals in the requirement around IF we feel that `_saleEndTimeStamp > block.timestamp` will evaluate to true more often than `_saleEndTimeStamp == 0`. Saves computation gas fees

2022-08-03 21:31 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        return blueprints[_blueprintID].saleState == SaleState.started && (blueprints[_blueprintID].saleEndTimestamp == 0 || block.timestamp <= blueprints[_blueprintID].saleEndTimestamp);
Accessing storage variables is expensive, so when you reference a variable in storage multiple times, you should cache it in a temporary variable first. 

In this case, I would consider turning the `isSaleEndTimestampCurrentlyValid` into a function that returns a boolean, and reusing it here. That way you pass in the timestamp once and don't have to reference `_blueprints` twice. Then, wherever you use `isSaleEndTimestampCurrentlyValid` as a modifier, simply bring it into the function it protects at the top, and stick it in a `require`.

2022-08-03 21:32 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        uint64 _maxPurchaseAmount,
Why did the uint type for `_maxPurchaseAmount` go up? Is that a part of the spec?

2022-08-03 21:34 UTC, beshup commented on contracts/contracts/BlueprintV12.sol
> +        // Do we want to validate that this is an accurate transition? i.e. not_started -> paused would be invalid, or enforce the modifiers on pause/unpause sale etc.
good question - let's list the invalid state changes and evaluate cost-benefit?

2022-08-03 21:37 UTC, beshup commented on test/admin-tests.js
> +    expect(result.saleState.toString()).to.be.equal(
You can group these expects, and expect the `result` object to look a certain way

2022-08-03 21:38 UTC, beshup commented on test/sales-tests.js
> +    // TODO: consider a test that shows you can't pause a sale who's end timestamp has passed...but maybe we don't want this if we want the minter to be able
@conlan thoughts here?

2022-08-03 21:38 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        require(_saleEndTimestamp == 0 || _saleEndTimestamp > block.timestamp, "Sale end timestamp is a past time");
good point, I assumed, since this is a new feature that probably more blueprints will choose to not specify, rather than specify. But we can check this w Conlan

2022-08-03 21:39 UTC, beshup requested changes
mostly LGTM, nice job! some gas recs

2022-08-03 21:44 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        uint256 saleEndTimestamp;
cool will reduce the size of the timestamp

2022-08-03 21:47 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        uint64 _maxPurchaseAmount,
just changed to align w the size in the `Blueprints` struct. not sure if its meant to be a u32 or a u64

2022-08-03 21:50 UTC, samwise2 commented on contracts/contracts/BlueprintV12.sol
> +        // Do we want to validate that this is an accurate transition? i.e. not_started -> paused would be invalid, or enforce the modifiers on pause/unpause sale etc.
Invalid:

not_prepared -> started
not_prepared -> paused
not_started -> paused
not_started -> not_prepared
started -> not_prepared
started -> not_started
paused -> not_prepared
paused -> not_started

2022-08-03 23:41 UTC, samwise2 commented on test/admin-tests.js
> +    expect(result.saleState.toString()).to.be.equal(
dug around a bit w this, the `result` object is super gross. It's an array with each of the properties unfolded with attached keys. So it's like a hacked array which also has properties. Doesn't play nicely with chai's `.to.include` assertions. If u want me to investigate more thoroughly lmk, but I think that's probably why the avolabs guys did it this way

2022-08-03 23:46 UTC, samwise2 commented on test/admin-tests.js
> +    expect(result.saleState.toString()).to.be.equal(
![Screen Shot 2022-08-03 at 7 45 31 PM](https://user-images.githubusercontent.com/24325294/182731557-b0ca944e-3b38-43d8-b88c-a3ece7722f41.png)
🤮

2022-08-05 18:26 UTC, samwise2 commented
going to squash and merge this into our dev branch, have some more PRs coming down the pipeline soon and want to avoid PR trains. I'll enumerate all the V12 changes when they're done and ping @conlan for a review once they are all in. @beshup let's continue trying to review one by one if possible

2022-08-05 18:30 UTC, beshup commented on test/admin-tests.js
> +    expect(result.saleState.toString()).to.be.equal(
You can just match with an array, you don't actually need to match with the object and the array (in my experience). And you can use `.eql` to deeply equal. But, happy to push this through, this is fairly inconsequential!

2022-08-05 18:31 UTC, beshup approved these changes

2022-08-05 18:37 UTC, merged

2022-08-10 21:10 UTC, conlan commented on test/sales-tests.js
> +    // TODO: consider a test that shows you can't pause a sale who's end timestamp has passed...but maybe we don't want this if we want the minter to be able
As per our meet yesterday, let's remove updateBlueprintSettings as that was a bandaid fix for some BP's. We shouldn't be relying on this moving forward.

2022-08-10 21:11 UTC, conlan commented on contracts/contracts/BlueprintV12.sol
> +        uint256 saleEndTimestamp;
End of the universe seems pretty safe!

2022-08-10 21:12 UTC, conlan commented on contracts/contracts/BlueprintV12.sol
> +        require(_saleEndTimestamp == 0 || _saleEndTimestamp > block.timestamp, "Sale end timestamp is a past time");
Actually this feature will be likely used pretty often as it guarantees that BP's will be closed out (sold our or closed) which lets the creator move on to their next project.

So more likely to be set than not.